# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b68dbd52fa6a645ff0e468f777ceed44117b0faf653a252cf265753cc0e7cd749001591a2f6cdbedc8a59ec3ebed932eae4362a5e26fdc61897dd17dccec3481

test:
  secret_key_base: ab1642a9a098ba4f99c1cb80db5d7c578813257ae46c75a3ab7eabefa840c395a10b1266a81addcf615662125081df5647a1197a6512ddc5cf567de4642878f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
